title: Jakub Nei
username: Jakub Nei
description-line-1: Game Developer
description-line-2: Unreal Engine & Unity

include_dir: "."
plugins:
  - jekyll-loading-lazy # Adds loading="lazy" to lazily load your images and iframes without the need for JavaScript.