title: Jakub Nei
username: Jakub Nei
description-line-1: Game Developer
description-line-2: Unreal Engine & Unity
github_username: jakubnei
instagram_username: jakub.neii
email: "%6e%65%69%2e%6a%61%6b%75%62%40%67%6d%61%69%6c%2e%63%6f%6d"

include_dir: "."
plugins:
  - jekyll-loading-lazy # Adds loading="lazy" to lazily load your images and iframes without the need for JavaScript.